sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  - "pypy"
  - "pypy3"

script:
  - for PYTHON in python python2 python3 python2.6 python2.7 python3.2 python3.3 python3.4 python3.5 python3.6 python3.7 pypy pypy2 pypy3 jython; do echo $PYTHON; $PYTHON --version || echo NOT FOUND; done

notifications:
  irc:
    channels:
      - "chat.freenode.net#o11c"
    template:
      - "plain \x02bold\x0f \x031,2color\x0f \x11monospace\x0f \x16reverse\x0f \x1ditalic\x0f \x1funderline\x0f"
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "%{result} (%{duration}) %{commit_subject}"
    use_notice: true
