language: cpp
install: ./do-install
script: ./do-build
# travis forces CC=gcc and CXX=g++
# and only support clang as an alternative
env:
 - REAL_CC=gcc-4.4 REAL_CXX=g++-4.4
 - REAL_CC=gcc-4.5 REAL_CXX=g++-4.5
 - REAL_CC=gcc-4.6 REAL_CXX=g++-4.6
 - REAL_CC=gcc-4.7 REAL_CXX=g++-4.7
 - REAL_CC=clang   REAL_CXX=clang++
