sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  - "pypy"
  - "pypy3"

script:
  - for PYTHON in python python2 python3 python2.6 python2.7 python3.2 python3.3 python3.4 python3.5 python3.6 python3.7 pypy pypy2 pypy3 jython; do echo $PYTHON; $PYTHON --version || echo NOT FOUND; done
