sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

script:
  - python --version
  - python2 --version
  - python3 --version
  - python2.6 --version
  - python2.7 --version
  - python3.2 --version
  - python3.3 --version
  - python3.4 --version
  - pypy --version
  - pypy3 --version
