#!/bin/sh
if [ "${REAL_CXX}" = "g++-4.7" ]
then
    # /test is for newer upstream releases; 4.6 is the last gcc in precise
    sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    sudo apt-get update
fi
sudo apt-get install "${REAL_CXX}"
